In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("synthetic_fraud_dataset.csv")
df.head(5)

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Date,Account_Balance,Device_Type,Location,Merchant_Category,Previous_Fraudulent_Activity,Daily_Transaction_Count,Card_Type,Card_Age,Fraud_Label
0,TXN_33553,USER_1834,39.79,POS,14 August 2023,93213.17,Laptop,Sydney,Travel,0,7,Amex,65,0
1,TXN_9427,USER_7875,1.19,Bank Transfer,7 June 2023,75725.25,Mobile,New York,Clothing,0,13,Mastercard,186,1
2,TXN_199,USER_2734,28.96,Online,20 June 2023,1588.96,Tablet,Mumbai,Restaurants,0,14,Visa,226,1
3,TXN_12447,USER_2617,254.32,ATM Withdrawal,7 December 2023,76807.20,Tablet,New York,Clothing,0,8,Visa,76,1
4,TXN_39489,USER_2014,31.28,POS,11 November 2023,92354.66,Mobile,Mumbai,Electronics,1,14,Mastercard,140,1

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Dataset shape:", df.shape)

Number of rows: 50000
Number of columns: 14
Dataset shape: (50000, 14)

In [5]:
print("Column Names:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Column Names:
1. Transaction_ID
2. User_ID
3. Transaction_Amount
4. Transaction_Type
5. Date
6. Account_Balance
7. Device_Type
8. Location
9. Merchant_Category
10. Previous_Fraudulent_Activity
11. Daily_Transaction_Count
12. Card_Type
13. Card_Age
14. Fraud_Label

In [6]:
df.dtypes

Transaction_ID                   object
User_ID                          object
Transaction_Amount              float64
Transaction_Type                 object
Date                             object
Account_Balance                 float64
Device_Type                      object
Location                         object
Merchant_Category                object
Previous_Fraudulent_Activity      int64
Daily_Transaction_Count           int64
Card_Type                        object
Card_Age                          int64
Fraud_Label                       int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Transaction_ID                50000 non-null  object
 1   User_ID                       50000 non-null  object
 2   Transaction_Amount            50000 non-null  float64
 3   Transaction_Type              50000 non-null  object
 4   Date                          50000 non-null  object
 5   Account_Balance               50000 non-null  float64
 6   Device_Type                   50000 non-null  object
 7   Location                      50000 non-null  object
 8   Merchant_Category             50000 non-null  object
 9   Previous_Fraudulent_Activity  50000 non-null  int64
 10  Daily_Transaction_Count       50000 non-null  int64
 11  Card_Type                     50000 non-null  object
 12  Card_Age                      50000 non-null  int64
 13  Fraud_Label                   50000 non-null  int64
dtypes: float64(2), int64(4), object(8)
memory usage: 5.3+ MB

In [8]:
df.isnull().sum()

Transaction_ID                  0
User_ID                         0
Transaction_Amount              0
Transaction_Type                0
Date                            0
Account_Balance                 0
Device_Type                     0
Location                        0
Merchant_Category               0
Previous_Fraudulent_Activity    0
Daily_Transaction_Count         0
Card_Type                       0
Card_Age                        0
Fraud_Label                     0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [13]:
Unique_values = pd.DataFrame({
    "Column": df.columns,
    "Unique_Values": df.nunique(),
    "Unique_Percentage": (df.nunique() / len(df) * 100).round(2)
})

Unique_values

,Column,Unique_Values,Unique_Percentage
Transaction_ID,Transaction_ID,50000,100.00
User_ID,User_ID,8963,17.93
Transaction_Amount,Transaction_Amount,21763,43.53
Transaction_Type,Transaction_Type,4,0.01
Date,Date,365,0.73
Account_Balance,Account_Balance,49867,99.73
Device_Type,Device_Type,3,0.01
Location,Location,5,0.01
Merchant_Category,Merchant_Category,5,0.01
Previous_Fraudulent_Activity,Previous_Fraudulent_Activity,2,0.00
Daily_Transaction_Count,Daily_Transaction_Count,14,0.03
Card_Type,Card_Type,4,0.01
Card_Age,Card_Age,239,0.48
Fraud_Label,Fraud_Label,2,0.00

In [14]:
categorical_columns = [
    "Transaction_Type",
    "Device_Type",
    "Location",
    "Merchant_Category",
    "Card_Type"
]

for column in categorical_columns:
    print("\n" + "=" * 60)
    print(f"{column}")
    print("=" * 60)
    print(df[column].unique())

============================================================
Transaction_Type
============================================================
['POS' 'Bank Transfer' 'Online' 'ATM Withdrawal']

============================================================
Device_Type
============================================================
['Laptop' 'Mobile' 'Tablet']

============================================================
Location
============================================================
['Sydney' 'New York' 'Mumbai' 'Tokyo' 'London']

============================================================
Merchant_Category
============================================================
['Travel' 'Clothing' 'Restaurants' 'Electronics' 'Groceries']

============================================================
Card_Type
============================================================
['Amex' 'Mastercard' 'Visa' 'Discover']

In [17]:
numeric_columns = df.select_dtypes(include=np.number).columns

print("Numerical columns:")
print(list(numeric_columns))

Numerical columns:
['Transaction_Amount', 'Account_Balance', 'Previous_Fraudulent_Activity', 'Daily_Transaction_Count', 'Card_Age', 'Fraud_Label']

In [18]:
numerical_summary = pd.DataFrame({
    "Mean": df[numeric_columns].mean(),
    "Median": df[numeric_columns].median(),
    "Std_Dev": df[numeric_columns].std(),
    "Minimum": df[numeric_columns].min(),
    "Q1": df[numeric_columns].quantile(0.25),
    "Q3": df[numeric_columns].quantile(0.75),
    "Maximum": df[numeric_columns].max(),
    "Skewness": df[numeric_columns].skew()
})

numerical_summary.round(2)

,Mean,Median,Std_Dev,Minimum,Q1,Q3,Maximum,Skewness
Transaction_Amount,99.41,69.66,98.69,0.00,28.68,138.85,1174.14,2.00
Account_Balance,50294.07,50384.43,28760.46,500.48,25356.00,75115.14,99998.31,-0.00
Previous_Fraudulent_Activity,0.10,0.00,0.30,0.00,0.00,0.00,1.00,2.70
Daily_Transaction_Count,7.49,7.00,4.04,1.00,4.00,11.00,14.00,0.00
Card_Age,120.00,120.00,68.99,1.00,60.00,180.00,239.00,0.00
Fraud_Label,0.32,0.00,0.47,0.00,0.00,1.00,1.00,0.77

In [20]:
for column in categorical_columns:
    print("\n" + "=" * 60)
    print(column)
    print("=" * 60)
    print(df[column].value_counts())

============================================================
Transaction_Type
============================================================
Transaction_Type
POS               12549
Online            12546
ATM Withdrawal    12453
Bank Transfer     12452
Name: count, dtype: int64

============================================================
Device_Type
============================================================
Device_Type
Tablet    16779
Mobile    16640
Laptop    16581
Name: count, dtype: int64

============================================================
Location
============================================================
Location
Tokyo       10208
Mumbai       9994
London       9945
Sydney       9938
New York     9915
Name: count, dtype: int64

============================================================
Merchant_Category
============================================================
Merchant_Category
Clothing       10033
Groceries      10019
Travel         10015
Restaurants     9976
Electronics     9957
Name: count, dtype: int64

============================================================
Card_Type
============================================================
Card_Type
Mastercard    12693
Visa          12560
Amex          12419
Discover      12328
Name: count, dtype: int64

In [24]:
print("\n" + "=" * 60)
print("Fraud Count")
print("=" * 60)
fraud_counts = df["Fraud_Label"].value_counts()

print(fraud_counts)
print("\n" + "=" * 60)
print("Fraud Percentage")
print("=" * 60)
fraud_percentage = df["Fraud_Label"].value_counts(normalize=True) * 100

print(fraud_percentage.round(2))

============================================================
Fraud Count
============================================================
Fraud_Label
0    33933
1    16067
Name: count, dtype: int64

============================================================
Fraud Percentage
============================================================
Fraud_Label
0    67.87
1    32.13
Name: proportion, dtype: float64

In [25]:
print("=" * 70)
print("STAGE 1 - DATASET UNDERSTANDING SUMMARY")
print("=" * 70)

print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
print(f"Missing Values: {df.isnull().sum().sum():,}")
print(f"Duplicate Rows: {df.duplicated().sum():,}")
print(f"Unique Transactions: {df['Transaction_ID'].nunique():,}")
print(f"Unique Users: {df['User_ID'].nunique():,}")
print(f"Fraud Transactions: {df['Fraud_Label'].sum():,}")
print(
    f"Fraud Rate: {df['Fraud_Label'].mean() * 100:.2f}%"
)

print("=" * 70)

======================================================================
STAGE 1 - DATASET UNDERSTANDING SUMMARY
======================================================================
Rows: 50,000
Columns: 14
Missing Values: 0
Duplicate Rows: 0
Unique Transactions: 50,000
Unique Users: 8,963
Fraud Transactions: 16,067
Fraud Rate: 32.13%
======================================================================